[package]
name = "sukurappa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.2.17", features = ["derive"] }
ureq = "2.5.0"
scraper = "0.13.0"